baseURL = '/'
languageCode = 'zh-CN'
title = '四十二阁'
theme = 'reimu'
defaultContentLanguage = 'zh-cn'

[languages]
  [languages.zh-cn]
    languageName = '中文'
    weight = 1
    title = '四十二阁'
  [languages.en]
    languageName = 'English'
    weight = 2
    title = 'Forty-Two Pavilion'

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS']

[taxonomies]
  category = 'categories'
  tag = 'tags'
